### ISSUE TITLE
Error: Expected a python object, received a character

### ISSUE THREAD

**Issue by UboCA** [scverse/anndataR#167] opened 2024-04-22 15:06 UTC
Hi, 

I am trying to load a h5ad file to R:
`mc = anndata::read_h5ad('metacells.h5ad')`
where the object seems to load correctly: `mc`

> AnnData object with n_obs × n_vars = 1558 × 22617
>     obs: 'grouped', 'total_umis', '__zeros_downsample_umis', 'u', 'v', 'w', 'x', 'y', 'compatible_size', 'hidden', 'obs_UMIs', 'obs_inner_normalized_variance', 'obs_inner_variance', 'type'
>     var: 'gene_ids', 'properly_sampled_gene', 'excluded_gene', 'clean_gene', 'related_genes_module', 'full_gene_index', 'rare_gene_module_0', 'rare_gene', 'lateral_gene', 'bursty_lonely_gene', 'marker_gene', 'feature_gene', 'top_feature_gene', 'var_UMIs', 'var_inner_normalized_variance', 'var_inner_variance'
>     uns: '__name__', 'mcview_format', 'metacells_algorithm', 'outliers'
>     layers: 'inner_fold', 'inner_variance_fold', 'total_umis', 'zeros'
>     obsp: 'obs_balanced_ranks', 'obs_outgoing_weights', 'obs_pruned_ranks', 'umap_distances'
>     varp: 'var_similarity'

However, when I tried to access `mc$obs` or `mc$var,` I get:

> Error: Expected a python object, received a character

Can anyone of you help me with this? Thank you.

Best

**Comment by lazappi** [comment] 2024-04-23 06:28
I think this is actually for the CRAN **{anndata}** package and is a duplicate of https://github.com/dynverse/anndata/issues/28. I am going to close this, please comment on the linked issue if needed.

**Closed by lazappi** 2024-04-23 06:28 UTC
